server:
  port: 8080
spring:
  application:
    name: service-a

  datasource:
    url: jdbc:postgresql://rc1d-3h7tsntvgduu8a1l.mdb.yandexcloud.net:6432/service-a
    username: jjagorka
    password: Shhdheh333.egdhhd

